name: Run tests

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Build with just
        run: just build-tests

      - name: Run tests
        run: ./bin/tests
